[package]
name = "rusted-invidious-types"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
scylla = "0.4"
chrono= "0.4"
tracing = "0.1"